import 'package:flutter/material.dart';

final List<Map<String, dynamic>> mockCategories = [
  {'id': 1, 'name': 'Desserts', 'image': const Placeholder()},
  {'id': 2, 'name': 'Main Course', 'image': const Placeholder()},
  {'id': 3, 'name': 'Appetizers', 'image': const Placeholder()},
  {'id': 4, 'name': 'Beverages', 'image': const Placeholder()},
];

final List<Map<String, dynamic>> mockRecipes = [
  {
    'id': 1,
    'name': 'Chocolate Cake',
    'category': 1,
    'image': const Placeholder(),
    'ingredients': ['2 cups flour', '1 cup sugar', '1/2 cup cocoa powder'],
    'steps': ['Mix ingredients', 'Bake at 350°F for 30 minutes'],
  },
  {
    'id': 2,
    'name': 'Apple Pie',
    'category': 1,
    'image': const Placeholder(),
    'ingredients': ['3 apples', '1 pie crust', '1/2 cup sugar'],
    'steps': ['Prepare apples', 'Bake at 375°F for 40 minutes'],
  },
  {
    'id': 3,
    'name': 'Tiramisu',
    'category': 1,
    'image': const Placeholder(),
    'ingredients': ['Ladyfingers', 'Mascarpone cheese', 'Espresso'],
    'steps': ['Layer ingredients', 'Chill for 4 hours'],
  },
  {
    'id': 4,
    'name': 'Cheesecake',
    'category': 1,
    'image': const Placeholder(),
    'ingredients': ['Cream cheese', 'Sugar', 'Graham crackers'],
    'steps': ['Prepare crust', 'Bake and chill'],
  },
  {
    'id': 5,
    'name': 'Grilled Chicken',
    'category': 2,
    'image': const Placeholder(),
    'ingredients': ['1 lb chicken', 'Salt', 'Pepper'],
    'steps': ['Season chicken', 'Grill until cooked through'],
  },
  {
    'id': 6,
    'name': 'Beef Stew',
    'category': 2,
    'image': const Placeholder(),
    'ingredients': ['1 lb beef', '2 cups broth', 'Vegetables'],
    'steps': ['Brown beef', 'Simmer with vegetables for 2 hours'],
  },
  {
    'id': 7,
    'name': 'Pasta Carbonara',
    'category': 2,
    'image': const Placeholder(),
    'ingredients': ['Spaghetti', 'Eggs', 'Bacon'],
    'steps': ['Cook pasta', 'Mix with sauce ingredients'],
  },
  {
    'id': 8,
    'name': 'Lamb Chops',
    'category': 2,
    'image': const Placeholder(),
    'ingredients': ['Lamb chops', 'Garlic', 'Rosemary'],
    'steps': ['Marinate lamb', 'Grill to desired doneness'],
  },
  {
    'id': 9,
    'name': 'Bruschetta',
    'category': 3,
    'image': const Placeholder(),
    'ingredients': ['Bread', 'Tomatoes', 'Basil'],
    'steps': ['Toast bread', 'Top with tomato and basil'],
  },
  {
    'id': 10,
    'name': 'Stuffed Mushrooms',
    'category': 3,
    'image': const Placeholder(),
    'ingredients': ['Mushrooms', 'Cheese', 'Breadcrumbs'],
    'steps': ['Stuff mushrooms', 'Bake at 375°F for 20 minutes'],
  },
  {
    'id': 11,
    'name': 'Deviled Eggs',
    'category': 3,
    'image': const Placeholder(),
    'ingredients': ['Eggs', 'Mayonnaise', 'Mustard'],
    'steps': ['Boil eggs', 'Stuff with filling'],
  },
  {
    'id': 12,
    'name': 'Mini Quiches',
    'category': 3,
    'image': const Placeholder(),
    'ingredients': ['Eggs', 'Cheese', 'Pastry dough'],
    'steps': ['Prepare dough', 'Fill with egg mixture and bake'],
  },
  {
    'id': 13,
    'name': 'Iced Coffee',
    'category': 4,
    'image': const Placeholder(),
    'ingredients': ['Coffee', 'Ice', 'Milk'],
    'steps': ['Brew coffee', 'Add ice and milk'],
  },
  {
    'id': 14,
    'name': 'Mango Smoothie',
    'category': 4,
    'image': const Placeholder(),
    'ingredients': ['Mango', 'Yogurt', 'Honey'],
    'steps': ['Blend ingredients', 'Serve chilled'],
  },
  {
    'id': 15,
    'name': 'Lemonade',
    'category': 4,
    'image': const Placeholder(),
    'ingredients': ['Lemons', 'Sugar', 'Water'],
    'steps': ['Mix ingredients', 'Serve over ice'],
  },
  {
    'id': 16,
    'name': 'Hot Chocolate',
    'category': 4,
    'image': const Placeholder(),
    'ingredients': ['Cocoa powder', 'Milk', 'Sugar'],
    'steps': ['Heat milk', 'Mix with cocoa and sugar'],
  },
];
